#include <gsl/gsl_const_mksa.h>

#define MEV_PER_RYD GSL_CONST_MKSA_RYDBERG / GSL_CONST_MKSA_ELECTRON_VOLT * 1000
#define RYD_PER_MEV GSL_CONST_MKSA_ELECTRON_VOLT / 1000 / GSL_CONST_MKSA_RYDBERG
#define AU_PER_ANGSTROM GSL_CONST_MKSA_ANGSTROM / GSL_CONST_MKSA_BOHR_RADIUS
#define ANGSTROM_PER_AU GSL_CONST_MKSA_BOHR_RADIUS / GSL_CONST_MKSA_ANGSTROM
